version: '3.6'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    tty: true
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - codenet

  app:
    build: ./node
    container_name: app
    restart: unless-stopped
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s node index.js
    tty: true
    volumes:
      - ./node:/usr/app
    depends_on:
      - db
    networks:
      - codenet

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - codenet

networks:
  codenet:
    name: codenet
    driver: bridge
     
